// Generated by `npx shadcn add @animate-ui/...`, then edited: the import was
// `motion/react`, which is a second copy of Framer Motion beside the
// `framer-motion` this project locks. Same API, so retargeting is enough.
// `add --overwrite` silently reverts this -- see docs/UI_GUIDE.md §2.
import * as React from 'react';
import { useInView, type UseInViewOptions } from 'framer-motion';

interface UseIsInViewOptions {
  inView?: boolean;
  inViewOnce?: boolean;
  inViewMargin?: UseInViewOptions['margin'];
}

function useIsInView<T extends HTMLElement = HTMLElement>(
  ref: React.Ref<T>,
  options: UseIsInViewOptions = {},
) {
  const { inView, inViewOnce = false, inViewMargin = '0px' } = options;
  const localRef = React.useRef<T>(null);
  React.useImperativeHandle(ref, () => localRef.current as T);
  const inViewResult = useInView(localRef, {
    once: inViewOnce,
    margin: inViewMargin,
  });
  const isInView = !inView || inViewResult;
  return { ref: localRef, isInView };
}

export { useIsInView, type UseIsInViewOptions };
